### ISSUE TITLE
Home Page UI: Better Layout

### ISSUE THREAD

**Issue by TroyFPV48** [SeattleColleges/nsc-events-android#105]
Solution: I want to create a better layout for the home page and a better placement for the buttons. Additionally I want the events to be in an event card allowing users to view the different events.

@Seiyaroo The current homepage is designed as a Login Page. Should I modify it to be the default user view UI and remove Login and Sign up buttons according to this [layout](https://github.com/SeattleColleges/nsc-events-android/wiki#nsc-mobile-app-layout)? Or to create a new screen for UserDefault view?

**Comment by Seiyaroo** [comment]
Sorry it took me so long to get to this @TroyFPV48 we are aiming to have the default landing page be what everyone sees. Elevated users will have the option to login but students wont need to login (or have the ability to) as far as I understand it. So I'd like to get @theGaryLarson say in on this but I believe that's our intent.
