### ISSUE TITLE
USER STORY: GitHub documentation

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/nsc-events-android#116]
As a developer and/or technical writer, I will want to make sure the team’s work is well documented. This will include further developing and creating consistency between the two client repos and their respective ReadMes and Wikis. 

I will want to work on and bring consistency to the following documents:
- [x] #124 
- [ ] nsc-events Wiki
- [x] #137
- [ ] nsc-events-android Wiki
- [ ] nsc-events-nestjs ReadMe
- [ ] nsc-events-nestjs Wiki

Also, within the "main" ReadMe (nsc-events) I will want to add the progress videos that the Product Owners have been sharing with clients, as well as a brief summary, listing them under MVP1 and MVP2 as appropriate.

**Note** To ensure consistency, I will want to ideally work on this task with two screens open at the same time. One open to the ReadMe or Wiki I am working on, one open to the same document belonging to the other client ReadMe/Wiki. I will also want to confer with my documentation counterpart on the other project as we plan a workflow that ensures we are consistent.

**Comment by taylorpapke** [comment]
@TroyFPV48 I am reassigning you to #135 since it is a user story that was never assigned for Sprint 4 and needs to be completed. Leadership team will complete documentation as we need all of our developers wrapping up the development portion of this project. My apologies for the last minute communication and changes. Thanks for creating the issues and the examples you provided!

**Comment by taylorpapke** [comment]
Hey @brandondombrowsky @brinkbrink What did we decide for the wiki sidebar? Do we want the built in sidebar on top with all the pages/contents or do we want the custom navigation sidebar bar on the bottom as well?

![Image](https://github.com/SeattleColleges/nsc-events-android/assets/94101953/20633e19-7057-42f2-bce6-fc673c62353d)

**Comment by brandondombrowsky** [comment]
I thought the decision had been made to do the Navigation style wiki and not the Pages style.

**Comment by taylorpapke** [comment]
Sounds good but I think it keeps both menus and collapses the top one from what I've noticed. The bottom menu links to the top but it's all under the hood.

**Comment by brandondombrowsky** [comment]
Can you make a note for us to discuss this in the leadership meeting? Or maybe @brinkbrink has an idea/plan as I know they did some wiki work in the past few days? Perhaps look in on their work to see until we have an answer from them?
