### ISSUE TITLE
USER STORY: Error handling async methods in activity services module (backend) 

### ISSUE THREAD

**Issue by Robel-003** [SeattleColleges/nsc-events-android#132]
I would like to ensure certain methods in the activity services module fail gracefully if an incorrect request is made. 

At the moment, the createEvent, updateActivityById, and DeleteActivityById async methods are not handling the error if an incorrect request is made so I would like to add error handling to these methods and throw the proper exceptions. To check if these methods are throwing the proper exceptions, use postman to test the api endpoints

Issues: 
- [ ] #156
- [ ] add error handling to the _updateActivityById_ method and throw the proper exceptions. Check if method is throwing the proper exceptions  using postman to test the api endpoints
- [ ] add error handling to the _ DeleteActivityById_ method and throw the proper exceptions. Check if method is throwing the proper exceptions  using postman to test the api endpoints

Resources:
- [nest.js documentation on exceptions](https://docs.nestjs.com/exception-filters)
- [YouTube link create unit tests](https://www.youtube.com/watch?v=GYHJYjQ1kYY&list=PL_cUvD4qzbkw-phjGK2qq0nQiG6gw1cKK&index=10) 
- [Example of testing api endpoints with postman](https://www.youtube.com/watch?v=PmY3UZGTFvY&list=PLdAEGQHOerPAMLdJim5Peryj6_2Q-477Z&index=5)

**Comment by taylorpapke** [comment]
Hey @Robel-003, please create an issue for https://github.com/SeattleColleges/nsc-events-nestjs/pull/48 when you get a chance
