### ISSUE TITLE
Front-End Research

### ISSUE THREAD

**Issue by Seiyaroo** [SeattleColleges/nsc-events-android#40]
As a developer, I will want to know about emerging technologies for Mobile Development and take into consideration the pros and cons of their usage in our project.

Describe the solution you'd like
Short pros and cons of the specific UI / Framework that is suggested for use. 

Include link(s) to relevant tutorial(s)
[Android Documentation](https://developer.android.com/develop/ui)
[Auth0 Documentation](https://auth0.com/docs/quickstarts)
[OAuth Documentation](https://oauth.net/2/)
Collaborate with developer(s) creating other UI components

**Comment by kaimanasse15** [comment]
Flutter:

Pros:

Cross-Platform Development: Flutter allows you to build apps for both Android and iOS with a single codebase, reducing development time and costs.
Rich UI: It provides a wide range of customizable UI widgets, allowing for the creation of visually appealing and interactive applications.
Fast Development: Hot-reload feature enables real-time code changes, making development faster and more efficient.
Strong Community: Flutter has a growing and active developer community, which means plenty of resources, plugins, and packages are available.
Cons:

Larger App Size: Flutter apps tend to have a slightly larger file size compared to native apps.
Performance: Although Flutter's performance is good, it may not match the native performance of certain complex applications.
Limited Native Module Access: Access to some platform-specific features might require additional development work.
Resources:

https://docs.flutter.dev/
https://docs.flutter.dev/get-started/codelab
https://pub.dev/
React Native:

Pros:

Cross-Platform Development: Similar to Flutter, React Native allows for building apps for both Android and iOS using a single codebase.
Native-Like Performance: React Native provides good performance and access to native modules, which can help achieve native-like experiences.
Huge Ecosystem: A vast ecosystem of third-party libraries and components are available via the npm package manager.
Facebook and Instagram: React Native is backed by Facebook, and both Facebook and Instagram apps are built using React Native, which underscores its capabilities.
Cons:

Bridge Communication: Communication between JavaScript and native modules can introduce a performance overhead.
Platform-Specific Code: Some platform-specific code is necessary for certain functionalities.
UI Consistency: Achieving pixel-perfect consistency across platforms can be challenging.
Resources:

https://reactnative.dev/
https://reactnative.dev/docs/environment-setup
https://reactnative.directory/

When deciding on a framework, it's important to collaborate closely with your team, including other developers responsible for creating UI components. Consider the specific needs of your project, such as performance requirements, design constraints, and the availability of development resources. Each project is unique, so it's essential to weigh the pros and cons carefully to make an informed decision.T
