### ISSUE TITLE
Bug Hunt (QA)

### ISSUE THREAD

**Issue by Seiyaroo** [SeattleColleges/nsc-events-android#43]
Feel free to list down your bug finds here. For now until a better approach is discussed, we will list all of our appropriate bugs that are discovered here.

Please provide the associated information:

**Method of Discovery**
IE: "I was clicking login, and my screen flickered and moved a div to the far side of my screen. My browser is Chrome Version 117.0.5938.132"

Don't hesitate to be as descriptive as possible so we can attempt to recreate the bug and work on a fix. You may also feel free to create a fix, but please document the solution, and let myself or someone else (PO, PM, Lead Dev, BC) know.

**Comment by MaddasaHatter** [comment]
No Back Button on Event Creation page
Clicking the "hamburger" menu causes app to crash
Click the "heart" causes app to crash
Click the "Pencil" causes app to crash
