### ISSUE TITLE
USER STORY: Registration Page

### ISSUE THREAD

**Issue by Seiyaroo** [SeattleColleges/nsc-events-android#46]
As a user, I would like to be able to have a registration page that will allow me to sign up for the application. 

**Describe the solution you'd like**
We need a basic Registration page that will have an associated form. Information on that form will be potentially:

**First Name:** Nick
**Last Name:** Di Pietro
**Student ID Number:**  123-45-6789
**Student or Faculty:**  Student
**Email Address:** FName.LName@email.com 

_Make sure you take note that names will be strings, id number is only Integer, Student or Faculty can be a drop down menu with 2 selectable options, and email address can be .edu, .com, .org, or any of the normally associated endings. Be sure to use type safety to avoid any potential bugs that arise from a client inputting incorrect information._

Related PR: #78

**Comment by taylorpapke** [comment]
Deleted duplicate user story #59 as this one already had a PR associated with it.
