### ISSUE TITLE
UA landing page UI

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/nsc-events-android#5]
## User Story

As a Web/Android Full Stack Developer, I will want to develop a very simple user authentication page. I will get in touch with the lead engineer should I have any questions or need support.

Story Points: 6-12

## Screenshot Example
 
![image](https://github.com/SeattleColleges/belindas-closet-nextjs/assets/91507453/fd19904a-9887-4027-8f91-11a012e2bdbb)

## Related Examples

- [Android login screen using Jetpack Compose part 1](https://medium.com/@manojbhadane/android-login-screen-using-jetpack-compose-part-1-57ecfc74e428)
- [Android login screen using Jetpack Compose Part 2](https://medium.com/@manojbhadane/android-login-screen-using-jetpack-compose-part-2-a262ad87c6d)

## References

- [Material Design for Android](https://developer.android.com/develop/ui/views/theming/look-and-feel)
- [Material Design](https://m3.material.io/)
- [Material Design 3 in Compose](https://developer.android.com/jetpack/compose/designsystems/material3)

**Comment by brandondombrowsky** [comment]
This Issues is complete, yes?

**Comment by tinpham5614** [comment]
Yes, it is complete.
