### ISSUE TITLE
Navbar Creation-Modification

### ISSUE THREAD

**Issue by theGaryLarson** [SeattleColleges/nsc-events-android#51]
As a front-end developer I will create a navbar containing buttons for the following links:

- [ ] Admin Page Link
- [ ] Create Event Page Link
- [ ] Filter Modal (filter by date and/or tags)

**Comment by kkennedy-gh** [comment]
After reading through [(https://developer.android.com/jetpack/compose/navigation)] and not being able to find a solution, I looked at the belindas_closet project to see how they set their routes up. 

I am thinking we should implement something similar to what they have in that project.

Are there any thoughts on this?

**Comment by taylorpapke** [comment]
Hey @kkennedy-gh, I was just curious if this was a duplicate for user story #58? If so, do you mind if I copy and paste everything from here into that user story and delete this one?

**Comment by kkennedy-gh** [comment]
Please go ahead and copy and paste it over and delete the other one.
