### ISSUE TITLE
USER STORY: Delete Events from Database

### ISSUE THREAD

**Issue by theGaryLarson** [SeattleColleges/nsc-events-android#54]
As a creator of an event. I want the ability to delete events that I create.

As an administrator I want the ability to delete events that I create or others have created.

### Three Roles:
-  user
- creator
- admin

The meaning of delete here is critical. We will want to make it appear as if it is deleted but not remove it form the database. This is known as a "soft delete". So basically we just need to flag it as hidden.

Tasks To Accomplish Goal:
- [x] Add boolean property to Event to track if an item is hidden. Use variable name `isHidden`. 
_If a creator clicks the delete button there will be an **update** to the database that sets the `isHidden` property to `true`_
- [x] Route needs setup on the backend to handle soft deletion.
- [x] [Frontend needs to make the call to backend to fulfill the request](https://github.com/SeattleColleges/nsc-events-android/issues/151)

Questions to ask yourself before getting started:
* Q: Where in the app will the delete button be located?
* Q: How will I avoid merge conflicts if I am creating this in collaboration with someone else?
_A: I will create the button in it's own composable where it can then be imported to the correct .kt file to be used._

Related issues #55 #50

**Comment by taylorpapke** [comment]
Edited the name of this user story to differentiate from user story #97. This user story focuses primarily on what happens in the backend when the delete button is pressed while #97 focuses on UI functionality for the same delete button along with a couple other buttons.
