### ISSUE TITLE
USER STORY: Display Event Details

### ISSUE THREAD

**Issue by theGaryLarson** [SeattleColleges/nsc-events-android#56]
As an user viewing events I want to see the time of the event and the location of the event. 
In both the `Event Card View` and the `Event Details View`

- [ ] DIsplay Time
- [ ] Location
- [ ] Upload a flyer to display. This could be a link that opens the document in the `Event Details View` and/or be uploaded as a background image on the `Event Card View`.

_These properties are already defined in the event. View the event schema and use the names there for reference._

### There are two main views for the Events.
* The Card View which shows in the Events View see diagram should be its own Composable.
* The Event View Details see diagram (Should be its own Composable).
## Front end
- will need to create the elements and style them.
- will need to load the data from the Event object.

**Comment by taylorpapke** [comment]
This user story was later duplicated as #71. #71 now has the pertinent PR's. I will copy and paste this user story #56 into #71 and then delete #56.
