### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by theGaryLarson** [SeattleColleges/nsc-events-android#58]
As a user I would like to have a nav bar at the top of my screen that is the same on every page. It would hold the links to the other pages of my app.

## Documentation
https://developer.android.com/jetpack/compose/components/scaffold
https://developer.android.com/jetpack/compose/components/app-bars

## Tutorials
https://www.youtube.com/watch?v=EqCvUETekjk

related issues: #59, #44 
- [ ] #82

### Add Cancel & Back button to all screens.
@kkennedy-gh please add the pages here in the checklist and create an issue for each one as you progress through them here.

- [x] #83
- [x] #86
- [x] #99
- [x] #107 
- [x] #119

Added from duplicate user story #51:
As a front-end developer I will create a navbar containing buttons for the following links:

- [ ] Admin Page Link
- [ ] Create Event Page Link
- [ ] Filter Modal (filter by date and/or tags)

**Comment by kkennedy-gh** [comment]
@theGaryLarson 

I am having difficulty with two Icon functions for this issue. I am missing something in the function, or the logic is incorrect. Could you take a look at these two screenshots and possibly suggest a next step I could take to continue?

<img width="1672" alt="Screenshot 2023-10-15 at 1 57 01 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/58679338/c5eb9afa-5128-437c-8066-7598bcaed131">
?
<img width="1672" alt="Screenshot 2023-10-15 at 1 56 47 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/58679338/6f25f6ba-1f49-42e0-b0ff-1d61e091e7f3">

**Comment by theGaryLarson** [comment]
@kkennedy-gh  can you push the branch you are currently working in so I can look it over locally? Let me know the branch name and when you get it pushed so I can check it out. Thanks!

**Comment by kkennedy-gh** [comment]
@theGaryLarson I will have it published by 4:30 for your review.

**Comment by taylorpapke** [comment]
Added contents of user story #51 here and then deleted it because it was a duplicate.
