### ISSUE TITLE
USER STORY: Home Page UI

### ISSUE THREAD

**Issue by Seiyaroo** [SeattleColleges/nsc-events-android#67]
As a user I want to ensure the home page routes to the User View (default page). Please see diagram below.

- [x] #105

Resource:
https://m3.material.io/

![NSC1](https://github.com/SeattleColleges/nsc-events-android/assets/37163331/46ceebc8-3016-4227-99fa-5f4f86cb5255)

- [ ] Specific Issue: I would like better visuals for the heading and font. Find something accessible, and not hard to read. Get it working in the app.
- [ ] Specific issue: I would like to create a sign-up and sign-in button and add it to the navbar. These buttons should have functionality routing users to their respective pages. 
~- [ ] Specific issue: I would like to create Event Card(s) depending on how many events there currently are. The event card needs minimal input fields such as title and date. The event cards need functionality routing user to the Events Detail View page~

**Comment by taylorpapke** [comment]
I updated this user story to remove the last issue associated because it was taken care of in a separate user story.
