### ISSUE TITLE
USER STORY: Events Details View Page

### ISSUE THREAD

**Issue by Robel-003** [SeattleColleges/nsc-events-android#71]
As a admin/creator I want to view and edit specific events 

**Solution:** I want to create a page that allows admins/creators to view events and to view and edit events, after they’ve clicked an event from the landing page

<img width="401" alt="Screenshot 2023-10-17 at 3 33 00 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/116779961/0ab9c4c8-5a02-474b-be64-7af0f416b803">

- [ ] **Issue:** expand the event card from the landing page into a new page, displaying the event in greater detail
_-In addition to the event name and date fields, I would like these non-editable input fields added; description, location, and a Img/Flier button attachment button_  

<img width="693" alt="Screenshot 2023-10-17 at 4 25 04 PM" src="https://github.com/SeattleColleges/nsc-events-android/assets/116779961/4d629350-7ac2-4fea-b181-9cdbd082e8c2">

- [ ] **Issue:** create an edit, delete, and an attend button that are functional only for admin
_-The edit button will allow admin to edit events in a separate page.
-The delete button will allow admin to delete events.
-The attend button will allow admin to increment the number of attendees for an event._

relates to issues: #76, #89 

Copied over from duplicate user story for more context:
As an user viewing events I want to see the time of the event and the location of the event. 
In both the `Event Card View` and the `Event Details View`

- [x] DIsplay Time
- [x] Location
- [ ] Upload a flyer to display. This could be a link that opens the document in the `Event Details View` and/or be uploaded as a background image on the `Event Card View`.

_These properties are already defined in the event. View the event schema and use the names there for reference._

### There are two main views for the Events.
* The Card View which shows in the Events View see diagram should be its own Composable.
* The Event View Details see diagram (Should be its own Composable).
## Front end
- will need to create the elements and style them.
- will need to load the data from the Event object.

**Comment by taylorpapke** [comment]
Copied over the contents from duplicate user story #56 for more context.
